# Generated by Django 3.2.14 on 2022-09-13 14:16

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique_for_date='created')),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='School event images', max_length=255, null=True)),
                ('address', models.CharField(max_length=225)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('speakers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('-created',),
            },
        ),
    ]
