# Generated by Django 3.2.14 on 2022-07-28 01:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique_for_date='created')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='School course images', max_length=255, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ('-created',),
            },
        ),
    ]
